In [0]:
!nvidia-smi

Fri Mar 20 15:03:23 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P0    30W / 250W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


# Install Mmdetection

In [0]:
# !ls "/content/drive/My Drive/TableBank/tablebank_latex" | wc -l
!rm -rf "/content/drive/My Drive/Mmdetection/mmdetection"

In [0]:
%cd "/content/drive/My Drive/Mmdetection"
!pip install -q mmcv terminaltables
!git clone 'https://github.com/open-mmlab/mmdetection.git'
%cd "/content/drive/My Drive/Mmdetection/mmdetection"
# build
!python setup.py install
!python setup.py develop
!pip install -r {"requirements.txt"}

/content/drive/My Drive/Mmdetection
     |████████████████████████████████| 61kB 2.5MB/s 
fatal: destination path 'mmdetection' already exists and is not an empty directory.
/content/drive/My Drive/Mmdetection/mmdetection
running install
running bdist_egg
running egg_info
writing mmdet.egg-info/PKG-INFO
writing dependency_links to mmdet.egg-info/dependency_links.txt
writing requirements to mmdet.egg-info/requires.txt
writing top-level names to mmdet.egg-info/top_level.txt
writing manifest file 'mmdet.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying mmdet/version.py -> build/lib.linux-x86_64-3.6/mmdet
running build_ext
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/mmdet
copying build/lib.linux-x86_64-3.6/mmdet/__init__.py -> build/bdist.linux-x86_64/egg/mmdet
copying build/lib.linux-x86_64-3.6/mmdet/version.py -> build/bdist.linux-x86_64/egg/mmdet
creating build/bdist.linux-x86_64/egg

In [0]:
both_images_file = open("/content/drive/My Drive/TableBank/both_images.txt","w")
latex_file = open("/content/drive/My Drive/TableBank/Latex.json","r")
latex_json = json.load(latex_file)
word_file = open("/content/drive/My Drive/TableBank/Word.json","r")
word_json = json.load(word_file)

total = 0
for idx,i in enumerate(latex_json['images']):
  if(idx < 500):
    continue
  if(idx > 1500):
    break
  total+=1
  both_images_file.write("/content/drive/My Drive/TableBank/tablebank_latex/"+str(i['file_name']))
  both_images_file.write("\n")

for idx,i in enumerate(word_json['images']):
  if(idx < 500):
    continue
  if(idx > 1500):
    break
  total+=1
  both_images_file.write("/content/drive/My Drive/TableBank/tablebank_word/"+str(i['file_name']))
  both_images_file.write("\n")

print(total)
both_images_file.close()
latex_file.close()
word_file.close()

2002


In [0]:
both_images_file = open("/content/drive/My Drive/TableBank/both_images.txt","r")
for i in both_images_file:
  print(i)
both_images_file.close()

/content/drive/My Drive/TableBank/tablebank_latex/1401.1298_12.jpg

/content/drive/My Drive/TableBank/tablebank_latex/1401.1298_13.jpg

/content/drive/My Drive/TableBank/tablebank_latex/1401.1298_15.jpg

/content/drive/My Drive/TableBank/tablebank_latex/1401.1298_6.jpg

/content/drive/My Drive/TableBank/tablebank_latex/1401.1298_7.jpg

/content/drive/My Drive/TableBank/tablebank_latex/1401.1298_9.jpg

/content/drive/My Drive/TableBank/tablebank_latex/1401.1303_7.jpg

/content/drive/My Drive/TableBank/tablebank_latex/1401.1310_10.jpg

/content/drive/My Drive/TableBank/tablebank_latex/1401.1310_11.jpg

/content/drive/My Drive/TableBank/tablebank_latex/1401.1310_2.jpg

/content/drive/My Drive/TableBank/tablebank_latex/1401.1310_3.jpg

/content/drive/My Drive/TableBank/tablebank_latex/1401.1310_7.jpg

/content/drive/My Drive/TableBank/tablebank_latex/1401.1310_8.jpg

/content/drive/My Drive/TableBank/tablebank_latex/1401.1310_9.jpg

/content/drive/My Drive/TableBank/tablebank_latex/1401.13

In [0]:
with open('/content/drive/My Drive/TableBank/Word.json') as f1:
	data1 = json.load(f1)
eval_images = open("/content/drive/My Drive/TableBank/both_images.txt","r")
e_images = []
for i in eval_images:
  e_images.append(i[:-1])
# e_images = e_images[:2000] 
# print(e_images) 
idx = 0
for i in data1['images']:
      image_name = "/content/drive/My Drive/TableBank/tablebank_both_augment/"+str(i['file_name'])
      if(image_name in e_images):
        print(image_name)
        idx+=1
print(idx)        

/content/drive/My Drive/TableBank/tablebank_both_augment/004_26648ns120914_22_24_1.jpg
/content/drive/My Drive/TableBank/tablebank_both_augment/005-CONSTRUCTION-MATERIALS_27.jpg
/content/drive/My Drive/TableBank/tablebank_both_augment/0053264_03132018_2.jpg
/content/drive/My Drive/TableBank/tablebank_both_augment/005_fonoaudiologas_4.jpg
/content/drive/My Drive/TableBank/tablebank_both_augment/006%20Enes%20Ha%C5%A1i%C4%87%20-%20ZRM_13.jpg
/content/drive/My Drive/TableBank/tablebank_both_augment/006%20Enes%20Ha%C5%A1i%C4%87%20-%20ZRM_14.jpg
/content/drive/My Drive/TableBank/tablebank_both_augment/006%20Enes%20Ha%C5%A1i%C4%87%20-%20ZRM_15.jpg
/content/drive/My Drive/TableBank/tablebank_both_augment/006%20Result%20EMBA%20Semester-V%20Fall%20%202017-20180410_0.jpg
/content/drive/My Drive/TableBank/tablebank_both_augment/006-Proposta-Comercial-E-09-106-302-2017_0.jpg
/content/drive/My Drive/TableBank/tablebank_both_augment/006-Proposta-Comercial-E-09-106-302-2017_5.jpg
/content/drive/My Dri

In [0]:
# %cd "/content"
%cd "/content/drive/My Drive/Mmdetection/mmdetection"

from collections import namedtuple
import numpy as np
import cv2
import glob
import time
import matplotlib
import matplotlib.pylab as plt
import glob
import mmcv
from mmcv.runner import load_checkpoint
import mmcv.visualization.image as mmcv_image
import lxml.etree as etree
import numpy as np
import os
import subprocess
import sys
from mmdet.models import build_detector
from mmdet.apis import inference_detector, show_result, init_detector
import cv2
import json

tablecount = 0

def bb_intersection_over_union(ground_truth, detection):
  global tablecount
  # print(tablecount)
  # determine the (x, y)-coordinates of the intersection rectangle
  tablecount+=1	
  xA = max(ground_truth[0], detection[0])
  yA = max(ground_truth[1], detection[1])
  xB = min(ground_truth[2], detection[2])
  yB = min(ground_truth[3], detection[3])
  # compute the area of intersection rectangle
  interArea = max(0, xB - xA + 1) * max(0, yB - yA + 1)
  # compute the area of both the prediction and ground-truth
  # rectangles
  gtArea = (ground_truth[2] - ground_truth[0] + 1) * (ground_truth[3] - ground_truth[1] + 1)
  detectionArea = (detection[2] - detection[0] + 1) * (detection[3] - detection[1] + 1)
  # compute the intersection over union by taking the intersection
  # area and dividing it by the sum of prediction + ground-truth
  # areas - the interesection area
  iou = interArea / float(gtArea + detectionArea - interArea)
  precision_iou = interArea / float(detectionArea)
  recall_iou = interArea / float(gtArea)
  precision.append(precision_iou)
  recall.append(recall_iou)

  # return the intersection over union value
  return iou

eval_images = open("/content/drive/My Drive/TableBank/both_images.txt","r")
e_images = []
for i in eval_images:
  e_images.append(i[:-1])
print(e_images)  
epochs = ['epoch_15.pth']
# Testing Images
# img_files = glob.glob("/content/drive/My Drive/TableBank/tablebank_both_augment/*.*")

with open('/content/drive/My Drive/TableBank/Latex.json') as f1:
	data1 = json.load(f1)
with open('/content/drive/My Drive/TableBank/Word.json') as f2:
	data2 = json.load(f2)

for epoch in epochs:
  tablecount = 0
  total = 0
  precision = []
  recall = []
  idx = 0
  try:
    score_thr = 0.92
    config_fname = "/content/drive/My Drive/cascade_mask_rcnn_hrnetv2p_w32_20e.py"
    checkpoint_file_path = "/content/drive/My Drive/both_cascade_mask_rcnn_hrnetv2p_w32_20e/"+epoch

    # build the model from a config file and a checkpoint file
    model = init_detector(config_fname, checkpoint_file_path)

    #{dict_keys(['info', 'licenses', 'images', 'categories', 'annotations'])}
    #{'file_name': '1401.0007_15.jpg', 'id': 1, 'license': 1, 'width': 596, 'height': 842}
    #{'segmentation': [[85, 396, 85, 495, 510, 495, 510, 396]], 'area': 42075, 'image_id': 1, 'category_id': 1, 'id': 1, 'iscrowd': 0, 'bbox': [85, 396, 425, 99]}

    gt_boxes = []
    t=0
    for i in data1['images']:
      gt_boxes = []		
      image_name = "/content/drive/My Drive/TableBank/tablebank_latex/"+str(i['file_name'])
      if(image_name not in e_images):
        continue
      if(cv2.imread(image_name) is None):
        print("continued1")
        continue  
      result = inference_detector(model, image_name)
      if(len(result[0][0])==0):
        print("continued1 again")
        continue
      total += 1
      d_bboxes = np.vstack(result)
      for j in data1['annotations']:
        if(j['image_id'] == i['id']):
          for k in j['segmentation']:
            gt_boxes.append(k)
      idx+=1
      print(i['id'],' ',idx,' ',i['file_name'])
      for bbox1 in d_bboxes[0][0]:
        min_dist = 99999
        min_el = gt_boxes[0][0]
        for bbox2 in gt_boxes:
          dist = np.linalg.norm((bbox1[0]-bbox2[0],bbox1[1]-bbox2[1]))
          if(min_dist > dist):
            min_dist = dist
            min_el = bbox2
        bbox_int1 = bbox1[:-1]
    
        t = t + 1
        total += 1
        bbox_int1 = bbox1.astype(np.int32)
        bbox_int2 = [int(min_el[0]),int(min_el[1]),int(min_el[4]),int(min_el[5])]
        iou = bb_intersection_over_union(bbox_int1,bbox_int2)
        print(" IOU : ",iou)

    gt_boxes = []		
    for i in data2['images']:
      gt_boxes = []		
      image_name = "/content/drive/My Drive/TableBank/tablebank_word/"+str(i['file_name'])
      if(image_name not in e_images):
        continue
      if(cv2.imread(image_name) is None):
        continue
      result = inference_detector(model, image_name)
      if(len(result[0][0])==0):
        continue
      total += 1
      d_bboxes = np.vstack(result)
      for j in data2['annotations']:
        if(j['image_id'] == i['id']):
          for k in j['segmentation']:
            gt_boxes.append(k)
      idx+=1
      print(i['id'],' ',idx,' ',i['file_name'])
      for bbox1 in d_bboxes[0][0]:
        min_dist = 99999
        min_el = gt_boxes[0][0]
        for bbox2 in gt_boxes:
          dist = np.linalg.norm((bbox1[0]-bbox2[0],bbox1[1]-bbox2[1]))
          if(min_dist > dist):
            min_dist = dist
            min_el = bbox2
        bbox_int1 = bbox1[:-1]
    
        # img = cv2.imread(image_name)
        # cv2.rectangle(img,(bbox_int1[0],bbox_int1[1]),(bbox_int1[2],bbox_int1[3]),(0,255,0))
        # cv2.imwrite(str(t)+".jpg",img)
        t = t + 1
        bbox_int1 = bbox1.astype(np.int32)
        bbox_int2 = [int(min_el[0]),int(min_el[1]),int(min_el[4]),int(min_el[5])]
        # bbox_int2 = bbox_int2.astype(np.int32)
        iou = bb_intersection_over_union(bbox_int1,bbox_int2)
        print(" IOU : ",iou)

  except Exception as e:
    print(str(e))

  # global tablecount
  print("total",total)

  sum_precision = sum(precision)
  sum_recall = sum(recall)

  avg_precision = sum_precision / tablecount
  avg_recall = sum_recall / tablecount

  f1_score = 2 * ((avg_precision * avg_recall) / (avg_precision + avg_recall))
  print("====================================================")
  print("Precision : ",avg_precision)
  print("Recall : ",avg_recall)
  print("F1 : ",f1_score)
  saver = "{} Paste in excel : {} {} {}".format(epoch,avg_precision,avg_recall,f1_score)
  print(saver)
  my_file = open("/content/file.txt", "w")
  my_file.write(saver)
  my_file.close()

Streaming output truncated to the last 5000 lines.
 IOU :  0.015273838097316169
 IOU :  0.7601208320937364
 IOU :  0.0
1321   1797   08172658_okullar_63.jpg
 IOU :  0.0
 IOU :  0.987670776407864
1322   1798   08172658_okullar_64.jpg
 IOU :  0.9090849409624204
1323   1799   08172658_okullar_72.jpg
 IOU :  0.9779946538318013
1324   1800   082-2017-o_27.jpg
 IOU :  0.9913958827152429
1325   1801   082-2017-o_35.jpg
 IOU :  0.979582875960483
1326   1802   082-2017-o_37.jpg
 IOU :  0.9529528236914601
1327   1803   082-2017-o_39.jpg
 IOU :  0.988298550674686
1328   1804   083%20all%20elenco%20corso%20ADVANCE%20_0.jpg
 IOU :  0.9864355533465872
1329   1805   08410200059Makalah%20TA%20Justin%20Lyonhart_5.jpg
 IOU :  0.8810661302489313
1330   1806   08410200059Makalah%20TA%20Justin%20Lyonhart_6.jpg
 IOU :  0.9896370245781564
 IOU :  0.0
1331   1807   08572-2016_16-0504.ord_35.jpg
 IOU :  0.9618896054945976
 IOU :  0.9945349487418453
1332   1808   08572-2016_16-0504.ord_36.jpg
 IOU :  0.98156259

# JSON Parsing

In [0]:
import time
import matplotlib
import matplotlib.pylab as plt
import glob
import mmcv
from mmcv.runner import load_checkpoint
import mmcv.visualization.image as mmcv_image
import lxml.etree as etree
import numpy as np
import os
import subprocess
import sys
from mmdet.models import build_detector
from mmdet.apis import inference_detector, show_result, init_detector
import cv2
import json

score_thr = 0.92
config_fname = "/content/drive/My Drive/cascade_mask_rcnn_hrnetv2p_w32_20e.py"
checkpoint_file_path = "/content/drive/My Drive/epoch_16.pth"

# build the model from a config file and a checkpoint file
model = init_detector(config_fname, checkpoint_file_path)

# Testing Images
img_files = glob.glob("/content/drive/My Drive/TableBank/tablebank_latex/*.*")

with open('/content/drive/My Drive/TableBank/Latex.json') as f:
  data = json.load(f)

#{dict_keys(['info', 'licenses', 'images', 'categories', 'annotations'])}
#{'file_name': '1401.0007_15.jpg', 'id': 1, 'license': 1, 'width': 596, 'height': 842}
#{'segmentation': [[85, 396, 85, 495, 510, 495, 510, 396]], 'area': 42075, 'image_id': 1, 'category_id': 1, 'id': 1, 'iscrowd': 0, 'bbox': [85, 396, 425, 99]}

gt_boxes = []
idx = 0
for i in data['images']:
  image_name = "/content/drive/My Drive/TableBank/tablebank_latex/"+str(i['file_name'])
  if(cv2.imread(image_name).shape is None):
    continue
  result = inference_detector(model, image_name)
  if(len(result)==0):
    continue
  d_bboxes = np.vstack(result)
  for j in data['annotations']:
    if(j['image_id'] == i['id']):
      for k in j['segmentation']:
        gt_boxes.append(k)
  idx+=1        
  print(i['id'],' ',idx)
  print(gt_boxes)
  print(d_bboxes[0][0])
  gt_boxes = []

1   1
[[85, 396, 85, 495, 510, 495, 510, 396]]
[[ 85.29179    395.89636    510.64343    494.18024      0.99991727]]
2   2
[[124, 84, 124, 141, 471, 141, 471, 84]]
[[123.81386     84.28481    472.13388    140.1818       0.99998677]]
3   3
[[327, 494, 327, 574, 552, 574, 552, 494]]
[[328.23267   493.786     550.5562    572.3368      0.9999851]]
4   4
[[93, 274, 93, 634, 518, 634, 518, 274]]
[[ 92.54744   273.3758    518.53015   632.4671      0.9998554]]
5   5
[[51, 291, 51, 500, 538, 500, 538, 291]]
[[ 51.57958    290.78488    537.71906    499.8482       0.99995065]]
6   6
[[51, 92, 51, 139, 407, 139, 407, 92]]
[[ 53.573414    90.827385   409.9018     136.98904      0.99993396]]
7   7
[[51, 92, 51, 140, 395, 140, 395, 92]]
[[ 52.61037    90.168205  457.8135    137.52429     0.9997788]]
8   8
[[318, 92, 318, 132, 474, 132, 474, 92]]
[[317.38797     92.33996    471.4036     129.8648       0.99997556]]
9   9
[[51, 540, 51, 683, 538, 683, 538, 540]]
[[ 74.12235     75.14125    533.54614    2

ValueError: ignored

# Evaluation Script

In [0]:
with open('/content/drive/My Drive/TableBank/both_aug.json') as f:
	data = json.load(f)
data['images']

[{'file_name': '%20Edward%20Dawes%20paper_13.jpg',
  'height': 842,
  'id': 0,
  'license': 1,
  'width': 596},
 {'file_name': 'dilate_%20Edward%20Dawes%20paper_13.jpg',
  'height': 842,
  'id': 1,
  'license': 1,
  'width': 596},
 {'file_name': 'smudge_%20Edward%20Dawes%20paper_13.jpg',
  'height': 842,
  'id': 2,
  'license': 1,
  'width': 596},
 {'file_name': '%20Edward%20Dawes%20paper_14.jpg',
  'height': 842,
  'id': 3,
  'license': 1,
  'width': 596},
 {'file_name': 'dilate_%20Edward%20Dawes%20paper_14.jpg',
  'height': 842,
  'id': 4,
  'license': 1,
  'width': 596},
 {'file_name': 'smudge_%20Edward%20Dawes%20paper_14.jpg',
  'height': 842,
  'id': 5,
  'license': 1,
  'width': 596},
 {'file_name': '%20Edward%20Dawes%20paper_15.jpg',
  'height': 842,
  'id': 6,
  'license': 1,
  'width': 596},
 {'file_name': 'dilate_%20Edward%20Dawes%20paper_15.jpg',
  'height': 842,
  'id': 7,
  'license': 1,
  'width': 596},
 {'file_name': 'smudge_%20Edward%20Dawes%20paper_15.jpg',
  'height':

In [0]:
# %cd "/content"
%cd "/content/drive/My Drive/Mmdetection/mmdetection"

from collections import namedtuple
import numpy as np
import cv2
import glob

import time
import matplotlib
import matplotlib.pylab as plt
import glob
import mmcv
from mmcv.runner import load_checkpoint
import mmcv.visualization.image as mmcv_image
import lxml.etree as etree
import numpy as np
import os
import subprocess
import sys
from mmdet.models import build_detector
from mmdet.apis import inference_detector, show_result, init_detector
import cv2
import json

def bb_intersection_over_union(ground_truth, detection):
	global tablecount
	# determine the (x, y)-coordinates of the intersection rectangle
	tablecount+=1	
	xA = max(ground_truth[0], detection[0])
	yA = max(ground_truth[1], detection[1])
	xB = min(ground_truth[2], detection[2])
	yB = min(ground_truth[3], detection[3])
	# compute the area of intersection rectangle
	interArea = max(0, xB - xA + 1) * max(0, yB - yA + 1)
	# compute the area of both the prediction and ground-truth
	# rectangles
	gtArea = (ground_truth[2] - ground_truth[0] + 1) * (ground_truth[3] - ground_truth[1] + 1)
	detectionArea = (detection[2] - detection[0] + 1) * (detection[3] - detection[1] + 1)
	# compute the intersection over union by taking the intersection
	# area and dividing it by the sum of prediction + ground-truth
	# areas - the interesection area
	iou = interArea / float(gtArea + detectionArea - interArea)
	precision_iou = interArea / float(detectionArea)
	recall_iou = interArea / float(gtArea)
	precision.append(precision_iou)
	recall.append(recall_iou)

	# return the intersection over union value
	return iou

epochs = ['epoch_9.pth','epoch_10.pth','epoch_11.pth','epoch_12.pth','epoch_13.pth']
# Testing Images
# img_files = glob.glob("/content/drive/My Drive/TableBank/tablebank_both_augment/*.*")

with open('/content/drive/My Drive/TableBank/both_test.json') as f:
	data = json.load(f)

for epoch in epochs:
	tablecount = 0
	precision =[]
	recall = []
	try:
		score_thr = 0.92
		config_fname = "/content/drive/My Drive/cascade_mask_rcnn_hrnetv2p_w32_20e.py"
		checkpoint_file_path = "/content/drive/My Drive/Mmdetection/both_table_cascade_mask_rcnn_hrnetv2p_w32_20e/"+epoch

		# build the model from a config file and a checkpoint file
		model = init_detector(config_fname, checkpoint_file_path)
		#{dict_keys(['info', 'licenses', 'images', 'categories', 'annotations'])}
		#{'file_name': '1401.0007_15.jpg', 'id': 1, 'license': 1, 'width': 596, 'height': 842}
		#{'segmentation': [[85, 396, 85, 495, 510, 495, 510, 396]], 'area': 42075, 'image_id': 1, 'category_id': 1, 'id': 1, 'iscrowd': 0, 'bbox': [85, 396, 425, 99]}

		gt_boxes = []
		idx = 0
		t=0
		for i in data['images']:
			# print(i)
			idx+=1        
			# if(idx <= 500):
			# 	continue
			# if(idx > 1502):
			# 	break
			image_name = "/content/drive/My Drive/TableBank/tablebank_both/"+str(i['file_name'])
			iii = cv2.imread(image_name)
			if(iii is None):
				print("continued")
				continue
			result = inference_detector(model, image_name)
			if(len(result[0][0])==0):
				print("continued again")
				continue

			hor,ver = line_detection(iii)

			# LINE CORRECTION
			if(hor is not None and ver is not None):    
				for r in result[0][0]:
					xmin = 9999
					ymin = 9999
					xmax = 9999
					ymax = 9999
					for h in hor:
						# print(h)
						diff1 = abs(h[1] - r[1])
						if(diff1 < abs(r[1]-ymin) and abs(h[0]-r[0])<25 and abs(h[2]-r[2])<25):
							ymin = h[1]
						diff2 = abs(h[3] - r[3])
						if(diff2 < abs(r[3]-ymax) and abs(h[0]-r[0])<25 and abs(h[2]-r[2])<25):
							ymax = h[3]    
					if(ymin != 9999):      
						r[1] = ymin
					if(ymax != 9999):      
						r[3] = ymax
					for v in ver:
						diff1 = abs(v[0] - r[0])
						if(diff1 < abs(r[0]-xmin) and abs(h[1]-r[1])<25 and abs(h[3]-r[3])<25):
							xmin = v[0]
						diff2 = abs(v[2] - r[2])
						if(diff2 < abs(r[2]-xmax) and abs(h[1]-r[1])<25 and abs(h[3]-r[3])<25):
							xmax = v[2]       
					if(xmin != 9999):        
						r[0] = xmin
					if(xmax != 9999):        
						r[2] = xmax    

				# BACK TO NORMAL 

			d_bboxes = np.vstack(result)
			for j in data['annotations']:
				if(j['image_id'] == i['id']):
					for k in j['segmentation']:
						gt_boxes.append(k)

			print(i['id'],' ',idx,' ',i['file_name'])
			# print(gt_boxes)
			# print(d_bboxes[0][0])
			# print("Image : {}".format(i))
			for bbox1 in d_bboxes[0][0]:
				min_dist = 99999
				min_el = gt_boxes[0][0]
				for bbox2 in gt_boxes:
					dist = np.linalg.norm((bbox1[0]-bbox2[0],bbox1[1]-bbox2[1]))
					if(min_dist > dist):
						min_dist = dist
						min_el = bbox2
				bbox_int1 = bbox1[:-1]
		
				# img = cv2.imread(image_name)
				# cv2.rectangle(img,(bbox_int1[0],bbox_int1[1]),(bbox_int1[2],bbox_int1[3]),(0,255,0))
				# cv2.imwrite(str(t)+".jpg",img)
				t = t + 1
				bbox_int1 = bbox1.astype(np.int32)
				bbox_int2 = [int(min_el[0]),int(min_el[1]),int(min_el[4]),int(min_el[5])]
				# bbox_int2 = bbox_int2.astype(np.int32)
				iou = bb_intersection_over_union(bbox_int1,bbox_int2)
				print(" IOU : ",iou)

			gt_boxes = []		

	except Exception as e:
		print("ERROR : ",str(e))

	# global tablecount

	sum_precision = sum(precision)
	sum_recall = sum(recall)

	avg_precision = sum_precision / tablecount
	avg_recall = sum_recall / tablecount

	f1_score = 2 * ((avg_precision * avg_recall) / (avg_precision + avg_recall))

	print("====================================================")
	print("Precision : ",avg_precision)
	print("Recall : ",avg_recall)
	print("F1 : ",f1_score)
	saver = "\n {} : {} {} {}".format(epoch,avg_precision,avg_recall,f1_score)
	print(saver)
	my_file = open("/content/drive/My Drive/newbothfile.txt", "a")
	my_file.write(saver)
	my_file.close()

Streaming output truncated to the last 5000 lines.
635   636   1-s2.0-S0305750X17300682-mmc1_5.jpg
 IOU :  0.9848609185319336
 IOU :  0.9848609185319336
45
(612, 792, 3)
636   637   1-s2.0-S0308814616310743-mmc1_15.jpg
 IOU :  0.9826954586583845
12
637   638   1-s2.0-S036013231300320X-mmc1_2.jpg
 IOU :  0.9731017455711006
137
(792, 612, 3)
638   639   1-s2.0-S036013231300320X-mmc1_35.jpg
 IOU :  0.9885425367091513
69
(792, 612, 3)
639   640   1-s2.0-S036013231300320X-mmc1_45.jpg
 IOU :  0.9874385921273553
32
(612, 792, 3)
640   641   1-s2.0-S0364591615002473-mmc1_3.jpg
 IOU :  0.9881125713628874
33
(612, 792, 3)
641   642   1-s2.0-S0364591615002473-mmc1_5.jpg
 IOU :  0.9813502369737788
23
(612, 792, 3)
642   643   1-s2.0-S0364591615002473-mmc1_7.jpg
 IOU :  0.9883968180297258
23
(612, 792, 3)
643   644   1-s2.0-S0364591615002473-mmc1_9.jpg
 IOU :  0.9834786180457304
6
(792, 612, 3)
644   645   1-s2.0-S073510971507758X-mmc1_2.jpg
 IOU :  0.9896731381667488
63
(842, 596, 3)
645   646   1

In [0]:
kjkjjbkjb kjbkb kjb kjb kjb kbk bk b khp jhpo jpo jo j

In [0]:
import cv2
import numpy as np

def line_detection(image):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    bw = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 3, 1)
    bw = cv2.bitwise_not(bw)
    horizontal = bw.copy()
    vertical = bw.copy()

    # [horiz]
    # Create structure element for extracting horizontal lines through morphology operations
    horizontalStructure = cv2.getStructuringElement(cv2.MORPH_RECT, (15, 1))

    # Apply morphology operations
    horizontal = cv2.erode(horizontal, horizontalStructure)
    horizontal = cv2.dilate(horizontal, horizontalStructure)

    horizontal = cv2.dilate(horizontal, (1,1), iterations=5)
    horizontal = cv2.erode(horizontal, (1,1), iterations=5)

    # cv2.imshow("hori",horizontal)
    # cv2.waitKey(0)
    hor_lines = cv2.HoughLinesP(horizontal,rho=1,theta=np.pi/180,threshold=100,minLineLength=150,maxLineGap=10)
    if hor_lines is None:
        return None,None
    temp_line = []
    for line in hor_lines:
        for x1,y1,x2,y2 in line:
            temp_line.append([x1,y1-5,x2,y2-5])

    hor_lines = sorted(temp_line,key=lambda x: x[1])
    print(len(hor_lines))
    for x1, y1, x2, y2 in hor_lines:
        cv2.line(image, (x1,y1-5), (x2,y2-5), (0, 255, 0), 1)

    

    # cv2.imshow("image",image)
    # cv2.waitKey(0)
    
    # [vert]
    # Create structure element for extracting vertical lines through morphology operations
    verticalStructure = cv2.getStructuringElement(cv2.MORPH_RECT, (1, 15))

    # Apply morphology operations
    vertical = cv2.erode(vertical, verticalStructure)
    vertical = cv2.dilate(vertical, verticalStructure)

    vertical = cv2.dilate(vertical, (1,1), iterations=5)
    vertical = cv2.erode(vertical, (1,1), iterations=5)

    ver_lines = cv2.HoughLinesP(vertical,rho=1,theta=np.pi/180,threshold=110,minLineLength=150,maxLineGap=10)
    if ver_lines is None:
        return None,None
    temp_line = []
    for line in ver_lines:
        for x1,y1,x2,y2 in line:
            temp_line.append([x1,y1-5,x2,y2-5])

    ver_lines = sorted(temp_line,key=lambda x: x[0])
    print(image.shape)
    for x1, y1, x2, y2 in ver_lines:
        cv2.line(image, (x1,y1-5), (x2,y2-5), (0, 255, 0), 2)
    return hor_lines,ver_lines

In [0]:
!ls "/content/drive/My Drive/TableBank/tablebank_both_augment/"

 000011_datretptc_r3_13_mar2017_12.jpg
 000011_datretptc_r3_13_mar2017_14.jpg
 000011_datretptc_r3_13_mar2017_15.jpg
 000011_datretptc_r3_13_mar2017_29.jpg
 000011_datretptc_r3_13_mar2017_30.jpg
 000011_datretptc_r3_13_mar2017_33.jpg
 000011_datretptc_r3_13_mar2017_34.jpg
 000011_datretptc_r3_13_mar2017_35.jpg
 000011_datretptc_r3_13_mar2017_36.jpg
 000011_datretptc_r3_13_mar2017_39.jpg
 000011_datretptc_r3_13_mar2017_44.jpg
 000011_datretptc_r3_13_mar2017_45.jpg
 000011_datretptc_r3_13_mar2017_7.jpg
 000011_datretptc_r3_13_mar2017_Japanese_25.jpg
 000011_datretptc_r3_13_mar2017_Japanese_26.jpg
 000011_datretptc_r3_13_mar2017_Japanese_27.jpg
 000011_datretptc_r3_13_mar2017_Japanese_6.jpg
 00005636_1.jpg
 000089795_4.jpg
 00011395_2.jpg
 000277572_3.jpg
 000317033_0.jpg
 000317045_0.jpg
 000318672_0.jpg
 000318722_0.jpg
 00031922-source_13.jpg
 00031922-source_18.jpg
 00031922-source_41.jpg
 00031922-source_58.jpg
 00031922-source_5.jpg
 00031922-source_62.jpg
 00031922-source_65.jpg
 0

# Scratch Work

In [0]:
from google.colab.patches import cv2_imshow

In [0]:
!curl -o logo.png https://colab.research.google.com/img/colab_favicon_256px.png
import cv2
import glob

paths = glob.glob("/content/*.jpg")
# print(paths)
for i in range(15):
  img = cv2.imread(paths[i], cv2.IMREAD_UNCHANGED)
  cv2_imshow(img)

In [0]:
result1 = inference_detector(model1, i)
result2 = inference_detector(model2, i)
bboxes1 = result1[0][0]
bboxes2 = result2[0][0]

for bbox1 in bboxes1:
  min_dist = 99999
  min_el = bboxes2[0]
  for bbox2 in bboxes2:
    dist = np.linalg.norm((bbox1[0]-bbox2[0],bbox1[1]-bbox2[1]))
    if(min_dist > dist):
      min_dist = dist
      min_el = bbox2
  idx+=1
  bbox_int1 = bbox1.astype(np.int32)
  bbox_int2 = min_el.astype(np.int32)

  # left_top1  = [bbox_int1[0],bbox_int1[1]]
  # left_top2  = [bbox_int2[0],bbox_int2[1]]
  # right_bottom1 = [bbox_int1[2],bbox_int1[3]]
  # right_bottom2 = [bbox_int2[2],bbox_int2[3]]

  # left_top = ((left_top1[0] + left_top2[0])//2,(left_top1[1] + left_top2[1])//2)
  # right_bottom = ((right_bottom1[0] + right_bottom2[0])//2,(right_bottom1[1] + right_bottom2[1])//2)
